Naam = input("wat is je naam? ")
Adres = input("wat is je adres? ")
Postcode = input("wat is je postcode? ")
Woonplaats = input("wat is je woonplaats? ")

print("----------------------------------------------------")
print(f"|  Naam      :  {Naam}                             ")
print(f"|  Adres     :  {Adres}                            ")
print(f"|  Postcode  :  {Postcode}                         ")
print(f"|  Woonplaats:  {Woonplaats}                       ")
print("----------------------------------------------------")